image: Ubuntu
version: '0.0.{build}'
configuration: Release
pull_requests:
  do_not_increment_build_number: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
before_build:
  - dotnet restore ./Carter.SirenNegotiator.sln 
  
build_script:
  - dotnet build --no-restore ./src/Carter.SirenNegotiator.csproj
  - dotnet build --no-restore ./sample/Carter.SirenNegotiator.Sample.csproj

before_deploy:
  - dotnet pack -o ../nupkgs --no-build --no-restore ./src/Carter.SirenNegotiator.csproj    

deploy:
  provider: NuGet
  api_key:
    secure: sVEOMjXCoYQU0B6tbPn7p/tEMMWqHXp3t78YZqRNgEABqKoveA8xsD4M5gMcqfSF
  artifact: ./nupkgs/*.nupkg