---
name: .Net Build
on:
  pull_request: null
  push:
    branches:
      - master
    tags:
      - "*"
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  build:
    name: Github Actions Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.*
      - name: Build Reason
        run: echo ${{github.ref}} and ${{github.event_name}}
      - name: Build
        run: dotnet build --configuration Release --nologo
