---
name: Publish Nuget
on:
  push:
    tags:
      - "*"
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  publish:
    name: Publish Nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.*
      - name: Publish Reason
        run: echo ${{github.ref}} and ${{github.event_name}}
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Pack project
        run: dotnet pack ./src/Carter.SirenNegotiator.csproj -c Release -p:PackageVersion=$VERSION
      - name: publish package
        run: dotnet nuget push ./src/bin/Release/Carter.SirenNegotiator.$VERSION.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
